# -*- coding: utf-8 -*-
"""clean_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15PyOrQYVWnxu0cgG1eXVABd8vyWS-K0w
"""

import pandas as pd

df=pd.read_csv('StudentsPerformance.csv')

df.head(10)

df.shape

df.isnull().sum() # Check for Null values

df.duplicated().sum() # Check for duplicates



